### ISSUE TITLE
Addon only send one image

### ISSUE THREAD

**Issue by curunoir** [hyperion-project/hyperion.kodi#10]
Hi, I have one issue using the xbmc addon with a remote hyperion server on rpi. When a video starts playing, the leds light on but they remain the same and never change. After that when I stop the play it light off so I'm pretty sure that the addon really communicate with the hyperion server. Another thing is that on some movies which first picture is colored, the leds are colored as well, but remain the same as if the addon captured and send always the same first image to the hyperion server.

This behaviour comes with only one of my device, an Android Tv box CSM8 with Android 4.4 and chipset ARM Amlogic S802. The Kodi is 14.1 and one the latest build for Android by the Kodi creators. But this is not only Android ! Indeed there is roms for this box to replace Android by Openelec so I installed OpenElec 5.0.3 on my box and I tried with it. The result was exactly the same ! Either with Android and Openelec...

Another information is that it is working with another devices :
- with the rpi itself when I play medias from it (there is memory leaks problem but that's another story)
- with my Windows 7 64 bits desktop with Kodi 14.1 over the network

Here is a pastebin of Kodi.log when the movie is playing nearly 22h25 http://pastebin.com/cNf3nAcL
and a pastebin of my hyperion conf file http://pastebin.com/LqpqNgYf

192.168.0.23 is the ip address of the client tv box, 192.168.0.19 is the ip address of the rpi with hyperion server, Xbmc Hyperion addon is configured toward this ip adress with default options

Please let me know how I can fix it or find clues of what's going on. If you have not much time I'm a developper and can modify the addon source to get information if you point me where and how I can inspect usefull datas.

Best regards.

**Comment by curunoir** [comment]
Could this be a defect in the CRenderCapture implementation onto this platform ? I don't know if this is relevant but i'm using the AmCodec hardware decoding method which is possible with S802 chipsets.

**Comment by ninovanhooff** [comment]
Is the initial colour always the same or dependent on movie content? In the
latter case, the script might not change state correctly between done
capturing and waiting for next capture (a new capture is not requested)
going back one version before my commit might work in that case

**Comment by curunoir** [comment]
It seems to change dependent on movie but it is not always the same colour for the same movie. I tried with the script.service.hyperion-2d52eacd8280905a8c2e2a6dbf539fc9d638bafd.zip commit and the behaviour is the same.

But minute I've just tested with disabling the Amcodec hardware decoding and... now it works ! Lights on and changing ! Yay ! But now the video playback is crap. Ugh.

**Comment by curunoir** [comment]
Also this is not related but is this normal than using playback locally on Rpi with Hyperion the kodi.bin process keeps growing in memory until it is rebooting ?

**Comment by brindosch** [comment]
@curunoir No
This addon is not for RPi, see wiki.

**Comment by curunoir** [comment]
well it is new

**Comment by brindosch** [comment]
Yes, hardware acceleration on android boxes is not supported

**Comment by curunoir** [comment]
Even on AML devices ? I found recent commits about an "amlgrabber" on hyperion sources but it may be only for Wetek devices on OpenElec system.
