### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by c3rv1x** [hyperion-project/hyperion.kodi#13]
I´ve used your addon on my old Apple TV (Crystalbuntu) for years without problems. Thanks for your efforts!

But the device is old, so I upgraded to a Cubox-i4 (ARM system with a linux-based distro called GeexBox). On this hardware the addon is not working anymore. If I start a movie, the system hangs forever.

Is this addon only working on x86-based systems? Or do I need to install addional software?

Would be cool if somebody could push me in the right direction.

**Comment by brindosch** [comment]
You may need to disable the hardware acceleration.
