### ISSUE TITLE
rework RenderCapture (Kodi)

### ISSUE THREAD

**Issue by iLLiac4** [hyperion-project/hyperion.kodi#15]
Hi. Can you please adopt this addon to the newly implemented changes in kodi?
https://github.com/xbmc/xbmc/pull/8613
http://forum.kodi.tv/showthread.php?tid=238393&pid=2193250#pid2193250

TNX

**Comment by b0mb** [comment]
i would also appreciate that ;)

**Comment by CalicodesIles** [comment]
+1 too. Thanks !

**Comment by brindosch** [comment]
Was done
