### ISSUE TITLE
LEDs go out in dark scenes..

### ISSUE THREAD

**Issue by thrash001** [hyperion-project/hyperion.kodi#19]
If at Kodi (15.2/16) a video is played in those dark scenes, the LEDs go out. Of course, go everything is black out but if they then hang the video afterwards if it continues. So the LEDs are off about 2-3 seconds. Is there a log where you can see what's going on? Is it in the video Dark, Night Scene, and only a few LEDs dark blue or brown to go from hyperion. It starts as I said a few seconds delay. If one then is startled one day to Scene when the room is bright at once.

in deutsch:
Wenn bei Kodi ein Video abgespielt wird in denen dunklen Szenen sind, gehen die LEDs aus. Natürlich gehen die aus wenn alles Schwarz ist aber sie hängen dann dem Video hinterher wenn es weiter läuft. Also die LEDs sind etwa 2-3 Sekunden aus. Gibt es ein Log wo man schauen kann was los ist? Ist es im Video dunkel, Nacht Szene, und nur einige LEDs zeigen dunkel blau oder braun an geht hyperion aus. Es startet wie gesagt mit einigen sekunden Verzögerung. Hat man dann eine Tag Szene erschrickt man wenn auf einmal das Zimmer hell wird.

**Comment by thrash001** [comment]
With the new version there no problems, solved bug

**Comment by brindosch** [comment]
oh, good to know ;)
