### ISSUE TITLE
Enable Grabbing Menus

### ISSUE THREAD

**Issue by siam28** [hyperion-project/hyperion.kodi#21]
Would it be possible to add grabbing menus to this addon?

**Comment by brindosch** [comment]
@iLLiac4 @Wolph
May you able to find a solution or answer? 
Would be great. 

Related to this and tune the addon a little bit i started this topic:
https://hyperion-project.org/threads/kodiaddon-more-options-and-enable-menu-grabbing.125/

If you are interested just give it a go :)

**Comment by wolph** [comment]
I'll take a look at it soon. Still processing the backlog of issues/pull requests on some of my other projects though :)

**Comment by RickDB** [comment]
Checked Kodi API and doesn't seem exposed atm :(

**Comment by brindosch** [comment]
You coud work around that maybe, if no other state  is defined, its menu. Enable disable grab  for all other states  (like kodi checker) would be nice to have

**Comment by RickDB** [comment]
Ah right, read this wrong and thought it was for UI grabbing.
Context menu is on the list and can be done based on Super Favorites :) , which isn't perfect but will do exactly this.

Probably for later release though was we still have to sort out some issues and improvements, after that new features 👍
