### ISSUE TITLE
integrate hyperion-dispmanx

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion.kodi#26]
on rpi switch to use the hyperion-dispmanx binary. All options in add on configuration are available as commandline options.

if addon is installed on rpi, the kodi-grabber code is disabled and hyperion-dispmanx is downloaded from git (or it is shipped with addon) and used for grabbing

**Comment by brindosch** [comment]
We could auto-install the kodi addon, but we might loose a little bit the "option" control over it.
