### ISSUE TITLE
ERROR: EXCEPTION Thrown (PythonToCppException) 

### ISSUE THREAD

**Issue by thebetterjort** [hyperion-project/hyperion.kodi#27]
Kodi v17 nightly build June 21st, 2016

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmc.RenderCapture' object has no attribute 'waitForCaptureStateChangeEvent'
                                            Traceback (most recent call last):

**Comment by brindosch** [comment]
Greetings,
could you please retest with the current Kodi 17 Beta.
Thanks

**Comment by brindosch** [comment]
This was a auto detection issue of the method. It should usually work, if erros persist we need to force it.
//waiting for feedback
