### ISSUE TITLE
exceptions.AttributeError

### ISSUE THREAD

**Issue by hyperops** [hyperion-project/hyperion.kodi#29]
exceptions.AttributeError

20:00:53 T:1453885744 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type:
  Error Contents: 'module' object has no attribute 'declare_namespace'
  Traceback (most recent call last):
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/addon.py", line 36, in
  from state import DisconnectedState
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/state.py", line 27, in
  from hyperion.Hyperion import Hyperion
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/hyperion/Hyperion.py", line 28, in
  from message_pb2 import HyperionRequest
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/hyperion.kodi-master/resources/lib/hyperion/message_pb2.py", line 6, in
  from google.protobuf import descriptor as descriptor
  File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.

**Comment by brindosch** [comment]
The android error the also saw @tpmodding 
@WoLpH will soon push a fix :)

**Comment by wolph** [comment]
Perhaps @RickDB and I will have some time to work on this and test this tonight :)

**Comment by tpmodding** [comment]
@WoLpH i'm at home, ready to test :)

**Comment by wolph** [comment]
Awesome! The current version is probably broken for you until the Kodi devs merge my pull requests:
- https://github.com/xbmc/repo-scripts/pull/265
- https://github.com/xbmc/repo-scripts/pull/266

For the time being I think you need to manually install the six addon: https://github.com/WoLpH/repo-scripts/tree/gotham/script.module.six
And the protobuf3 addon: https://github.com/WoLpH/repo-scripts/tree/protobuf3/script.module.protobuf3

Just dump those directories in your kodi addons folder and you should be done :)

**Comment by brindosch** [comment]
wow, i didn't noticed you are working that much on it :)
As written they wait for a hyperion kodi addon push from our side until you get proto3

**Comment by wolph** [comment]
That's the case for the protobuf3 library but I'm not sure why they are not merging the protobuf2 library

**Comment by tpmodding** [comment]
but we have little things to do :) did you update something?

**Comment by wolph** [comment]
I haven't been able to get the Android version completely up and running yet unfortunately. Still working on it though, in addition to a few other projects that is

**Comment by razzeee** [comment]
Sorry to ask here in that fashion, but I'm really curious what your working on in regards to android and hyperion :)
@WoLpH

**Comment by wolph** [comment]
For some reason the Android version of Kodi is using a different screen grabbing method which causes the addon to work for the first frame and stop after that. Once that's working Hyperion should function using Android devices as well :)

**Comment by razzeee** [comment]
So running the server on android?
I just setup my (android/nvidia shield + kodi + hyperion client) + (rpi + hyperion server) today.
Seems to work in videos with kodi v17 as long as you turn off surface rendering.

**Comment by tpmodding** [comment]
what happens if you turn rendering on? 

is your system rooted?

**Comment by razzeee** [comment]
It stops working. Not rooted, but dev tools might be active.

**Comment by wolph** [comment]
In that case it might have been something I broke, could be something else. I just need time to investigate :)

**Comment by razzeee** [comment]
Just to clarify, I'm not using master, but https://github.com/hyperion-project/hyperion.kodi/releases/tag/V1.0.2
