### ISSUE TITLE
Running Addon on Android ?

### ISSUE THREAD

**Issue by curunoir** [hyperion-project/hyperion.kodi#3]
Hi !

Since there are now XBMC running on Android, will this addon works on these devices ? Does the screen grabbing works without other libraries / dependencies ?

Bye !

**Comment by ninovanhooff** [comment]
I got it working on Ouya, which has Android at the core. But see https://github.com/poljvd/script.service.hyperion/issues/4

**Comment by ninovanhooff** [comment]
#5 fixes #3. This issue can be closed.
