### ISSUE TITLE
hardware acceleration

### ISSUE THREAD

**Issue by edwinvd1** [hyperion-project/hyperion.kodi#32]
Disable on android boxes/system the hardware acceleration. 
this can be fixed it?

**Comment by ziggy73701** [comment]
Fixed if you are running SPMC

**Comment by sivilya** [comment]
Any plans to fix for kodi 17 (krypton)?

**Comment by bpavlov** [comment]
I am not sure that it is fixed even in SPMC. I have the same problem.
