### ISSUE TITLE
Enable addon (grabbing) setting doesn’t work

### ISSUE THREAD

**Issue by horstepipe** [hyperion-project/hyperion.kodi#36]
Hey
Doesn’t matter whether I enable or disable this option in Hyperion settings in Kodi, the lights are always turned on.
Only workaround is to disable the addon completely, which unfortunately makes Kodi freeze when something is playing back meanwhile.

**Comment by MartB** [comment]
https://github.com/hyperion-project/hyperion.kodi/blob/1747c117293f9bbc277f28ff8a86a3bd5813ac0c/resources/lib/settings.py#L75

and 

https://github.com/hyperion-project/hyperion.kodi/blob/1747c117293f9bbc277f28ff8a86a3bd5813ac0c/resources/lib/settings.py#L76

should be

```python
self.enable = addon.getSetting('hyperion_enable').lower() == 'true'
self.enableScreensaver = addon.getSetting('screensaver_enable').lower() == 'true'
```
