### ISSUE TITLE
Kodi error message for hyperion ambilight

### ISSUE THREAD

**Issue by thehaunted318** [hyperion-project/hyperion.kodi#54]
Ater installing the add on in Kodi, I get the following error in the Kodi log:
  hyperion.kodi version v20.0.1 - Nexus
Kodi version 20.2 and 20.0
Windows 10 ad Windows 11
`error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'ABCMeta' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\service.py", line 29, in <module>
                                                       from resources.lib.monitor import HyperionMonitor
                                                     File "C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\resources\lib\monitor.py", line 34, in <module>
                                                       State = Callable[[], "State"]
                                                   TypeError: 'ABCMeta' object is not subscriptable
                                                   -->End of Python script error report<--`

**Comment by Lord-Grey** [comment]
@sanzoghenzo Would be you ok having a look at the reported issue?

**Comment by sanzoghenzo** [comment]
Shoot, I imported the wrong Callable, damn IDE :sweat_smile: 
[This line](https://github.com/hyperion-project/hyperion.kodi/blob/master/script.service.hyperion/resources/lib/monitor.py#L24) should be changed to `from typing import Callable`

**Comment by Lord-Grey** [comment]
@sanzoghenzo Thank you for the quick turnaround and provided fix!

**Comment by Lord-Grey** [comment]
@thehaunted318 I updated the 20.0.1 release with a zip that contains a correction.
May I ask you to test, if the new plugin works?

**Comment by thehaunted318** [comment]
The error in the kodi log is now different:
`EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'type' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\service.py", line 29, in <module>
                                                       from resources.lib.monitor import HyperionMonitor
                                                     File "C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\resources\lib\monitor.py", line 37, in <module>
                                                       class HyperionMonitor(xbmc.Monitor):
                                                     File "C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\resources\lib\monitor.py", line 117, in HyperionMonitor
                                                       def get_capture_size(self) -> tuple[tuple[int, int], int]:
                                                   TypeError: 'type' object is not subscriptable
                                                   -->End of Python script error report<--`

**Comment by Lord-Grey** [comment]
@sanzoghenzo ???

**Comment by sanzoghenzo** [comment]
I don't have a windows box to test it, but it seems that the windows version comes with an older python interpreter (< 3.9).
I couldn't find any information about the packaged python version, and I went with 3.10.

@thehaunted318 could you please try to add the line
`from __future__ import annotations`
At the beginning of the file `C:\Users\denni\AppData\Roaming\Kodi\addons\script.service.hyperion\resources\lib\monitor.py` and see if it works?

**Comment by thehaunted318** [comment]
Error message and errors in the log are gone now.
Everything works perfectly now.
Thanks a lot!
