### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SakeyJakey** [hyperion-project/hyperion.kodi#60]
I have checked PROTO server port and it is not a Hyperion output issue as when it boots up, the rainbow animation plays.

**Comment by Lord-Grey** [comment]
Would be good, if you could share more details...
What Version of the plugin are you running and on which Operating System and which hardware?

**Comment by SakeyJakey** [comment]
Plugin Version: 20.0.1
Operating System: LibreELEC
Hardware: Raspberry Pi 3 Model B

**Comment by Lord-Grey** [comment]
@SakeyJakey I would suggest you install the latest published [release](https://github.com/hyperion-project/hyperion.kodi/releases/tag/v20.0.2) and if that does not work, read the release notes…

**Comment by SakeyJakey** [comment]
After updating, it still doesn't work

**Comment by Lord-Grey** [comment]
> if that does not work, read the release notes…

„This plugin does not work for Kodi running on Raspberry Pi. There is an outstanding Kodi fix for that.“

**Comment by SakeyJakey** [comment]
Outstanding Kodi fix?

**Comment by fightforlife** [comment]
Since I just saw this:
For me Plugin Version 20.0.2 in kodi-gles 21.0-7 on Arch Linux (Docker x86_64) is working fine.

**Comment by Lord-Grey** [comment]
> Outstanding Kodi fix?

See https://github.com/xbmc/xbmc/pull/18741

**Comment by SakeyJakey** [comment]
Could I use a HDMI grabber and feed it back into th Pi?

**Comment by Lord-Grey** [comment]
> Could I use a HDMI grabber and feed it back into th Pi?

Yes

**Comment by SakeyJakey** [comment]
Now my audio seems to be using the light data. I am using the audio jack not HDMI.
