### ISSUE TITLE
unable to send image 32101

### ISSUE THREAD

**Issue by nilshomeier** [hyperion-project/hyperion.kodi#8]
Hi.
I'm running Kodi with this script on Ubuntu 14.04.1 LTS - KODIbuntu (GNU/Linux 3.13.0-44-generic x86_64). Hyperion daemon is running on a BananaPi with Debian Wheezy Bananian OS. WS2801 are connected directly on the BPI over GPIO SPI.
Communication over LAN works fine; I can set colors and effects from HTPC over LAN just fine. First test with video files was successful too.
Then on the next day I continued with setting up the system and configured lirc. Once that was done I started a video and got a popup "Unable to send image to server". 
I checked the server on the BPi and saw it had stopped. So I started it manually from a ssh and got this response from hyperion when a video is played:

Json connection closed
New json connection
hyperiond: /root/hyperion/dependencies/build/jsoncpp/json_value.cpp:1176: const Json::Value& Json::Value::operator[](const char*) const: Assertion `type_ == nullValue || type_ == objectValue' failed.
[1]    2284 abort (core dumped)  hyperiond /etc/hyperion.config.json

Do you have any idea, what might be causing this error and/or what can be done to fix it?

**Comment by alextoff** [comment]
My Hyperion setup was working perfectly until I stupidly uninstalled xbmc and did a clean install of Kodi.  Now I have the same problem.  I receive the error "unable to send image to hyperion."  I tried installing the older version of XBMC to see if it's just an issue with Kodi, but it's not, I receive the same error with both.  Leads me to believe there was some kind of config file that I had in the xbmc directory that made it all work.  

I can get the boblight xbmc/kodi plugin to work with hyperion using port 19333, but the Hyperion plugin using port 19445 just gives me that "unable to send image to hyperion" error.

Appreciate any help!
